// vue/src/components/Header.vue
<template>
<header class="header">
    <label>Current User: {{name}}</label>
        <input type="text" v-model="changeUser"> 
         <button @click="submit">
            Apply
        </button>
</header>
</template>
<script lang="ts">
import Vue from 'vue'
export default Vue.extend ({
  name: 'Header',
  data() {
    return {
        name: "TestUser",
        changeUser:""
    }
  },
  methods : {
      submit(){
          this.name = this.changeUser
      }
   }
})
</script>

// react/src/Header.tsx
import React from "react"

export const Header = () => {
    const [name, setName] = React.useState("Test User")
    const [changeName, setChangeName] = React.useState("")
    return (<header className={"header"}>
        <label>Current User: {name}</label>
        <input value={changeName} onChange={(ev) => {
            ev.preventDefault();
            setChangeName(ev.target.value)
        }} />
        <button onClick={(ev) => {
            setName(changeName)
        }}>
            Name aendern
    </button>

    </header>)
}
