// vue/src/components/Question.vue
<template>
    <label>{{question.question}}...
        <button v-bind:class="{false:lock && (answer !== option), correct:lock && (answer === option)}" v-for="option in question.options" :key="option" @click="handleClick(option)">
            {{option}}
        </button>
    </label>
</template>
<script lang="ts">
import Vue, { PropType } from 'vue'
import {Question} from '../FakeData'
export default Vue.extend({
    data(){
        return {
            answer:this.question.answer,
            lock:false,
            state:{isAnwered:false,isCorrect:false}
        }
    },
  props: {
    question: {} as PropType<Question>,
  },
  methods:{
      handleClick(value:string){
        if(!this.lock){
            if(this.answer === value){
            this.$emit("question-answered",{isAnswered:true,isCorrect:true})
        }
        else{
            this.$emit("question-answered",{isAnswered:true,isCorrect:false})
        }
        this.lock = true
        }
      }
  }
})
</script>

// react/src/Question.tsx
import React from "react"
import { Question } from "./fakeData"

export interface ListItemProps {
    lock: boolean
    value: string,
    answer: string
    isCorrect: (val: boolean) => void
}
export interface ListProps {
    question: Question
    update: (state: {
        isCorrect: boolean,
        isAnswered: boolean
    }) => void
}
export const QuestionWrapper: React.FC<ListProps> = (props) => {
    const [lock, setLock] = React.useState(false)
    const isCorrect = (bool: boolean) => {
        setLock(true);
        props.update({ isAnswered: true, isCorrect: bool })
    }
    return (
        <>
            <div className="card">
                <label>{props.question.question}
                    <br />
                    {props.question.options.map((option, idx) => <QuestionItem
                        key={idx}
                        value={option}
                        answer={props.question.answer}
                        isCorrect={isCorrect}
                        lock={lock} />)}
                </label>
            </div>

        </>
    )
}
export const QuestionItem: React.FC<ListItemProps> = (props) => {
    const [isClicked, setIsClicked] = React.useState(false)
    const displayClassName = () => {
        if (props.lock) {
            if (props.value === props.answer) {
                return "correct"
            }
            else {
                return "false"
            }
        }
        return ""
    }
    return (<>
        <button onClick={(e => {
            e.preventDefault()
            if (!props.lock) {
                if (props.value === props.answer) {
                    props.isCorrect(true)
                }
                else {
                    props.isCorrect(false)
                }
                setIsClicked(true)
            }
        })}
            className={`${displayClassName()} ${isClicked ? "active" : ""}`}>
            {props.value}
        </button>
    </>)
}
